sudo: false
git:
  depth: 2
language: node_js
node_js:
  - iojs
  - node
script: npm run-script pretest && npm run-script coverage
after_script:
  - npm install istanbul-coveralls
  - node node_modules/.bin/istanbul-coveralls
